# Generated by Django 5.1.1 on 2024-11-18 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='unique_id',
            new_name='category_id',
        ),
    ]
