# Generated by Django 5.1.1 on 2024-11-19 08:44

import customAdmin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0004_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='model',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_id',
            field=models.IntegerField(default=customAdmin.models.generate_unique_id, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_id',
            field=models.IntegerField(default=customAdmin.models.generate_unique_id, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='model',
            name='model_id',
            field=models.IntegerField(default=customAdmin.models.generate_unique_id, editable=False, unique=True),
        ),
    ]
