# Generated by Django 5.1.1 on 2024-11-23 10:46

import customAdmin.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0005_alter_brand_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('specification_id', models.IntegerField(default=customAdmin.models.generate_unique_id, editable=False, primary_key=True, serialize=False, unique=True)),
                ('model_name', models.CharField(max_length=255)),
                ('brand_name', models.CharField(max_length=255)),
                ('ram', models.CharField(max_length=50)),
                ('storage', models.CharField(max_length=50)),
                ('battery', models.CharField(max_length=50)),
                ('sim_type', models.CharField(max_length=50)),
                ('e_sim', models.BooleanField(default=False)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='customAdmin.model')),
            ],
            options={
                'verbose_name_plural': 'Specifications',
                'ordering': ['model__name', 'ram'],
            },
        ),
    ]
