# Generated by Django 5.1.1 on 2024-11-23 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0006_specification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='model_name',
        ),
    ]
