# Generated by Django 5.1.1 on 2024-11-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0007_remove_specification_brand_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='e_sim',
            field=models.CharField(default='yes', max_length=50),
        ),
    ]
