# Generated by Django 5.1.1 on 2024-11-21 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_shopregistration_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopDetail',
            fields=[
                ('SDid', models.AutoField(primary_key=True, serialize=False)),
                ('shop_open', models.DateTimeField(blank=True, null=True)),
                ('shop_close', models.DateTimeField(blank=True, null=True)),
                ('holiday_mode', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop_images/')),
                ('fk_ShopID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop_detail', to='seller.shopregistration')),
            ],
        ),
    ]
