# Generated by Django 5.1.1 on 2024-11-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0009_shopdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopdetail',
            name='policy',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='shopdetail',
            name='image',
            field=models.ImageField(null=True, upload_to='shop_images/'),
        ),
    ]
