# Generated by Django 5.1.1 on 2024-11-21 17:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0010_shopdetail_policy_alter_shopdetail_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='addProduct',
            fields=[
                ('productID', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('imei', models.CharField(max_length=255)),
                ('condition', models.CharField(max_length=255)),
                ('colors', models.CharField(max_length=255)),
                ('color2', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('seller_sku', models.CharField(max_length=255)),
                ('exchange', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('fk_ShopID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addproduct', to='seller.shopregistration')),
            ],
        ),
        migrations.CreateModel(
            name='productImage',
            fields=[
                ('productImageID', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(null=True, upload_to='productimages/')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('fk_addProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productimage', to='seller.addproduct')),
            ],
        ),
    ]
