# Generated by Django 5.1.1 on 2024-11-21 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0011_addproduct_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addproduct',
            old_name='brand',
            new_name='brand1',
        ),
    ]
